# Generated by Django 5.0 on 2025-08-05 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HotelCustomerQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("customer_query_message", models.TextField()),
                ("ai_email_response", models.TextField()),
                ("phone_number", models.CharField(max_length=50, null=True)),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "language_mode",
                    models.CharField(
                        choices=[("English", "English"), ("Spanish", "Spanish")],
                        default="English",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelCustomerVoiceCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("caller_name", models.CharField(max_length=150, null=True)),
                ("phone_number", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("location", models.CharField(max_length=150, null=True)),
                ("call_summary", models.TextField()),
                ("call_transcript", models.TextField()),
                ("recording_url", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HotelEnglishSpeakingCustomerQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=254)),
                ("customer_query_message", models.TextField()),
                ("customer_comments", models.TextField()),
                ("ai_assistant_response", models.TextField()),
                ("laundry_event_details", models.TextField()),
                ("location", models.CharField(max_length=150)),
                ("timestamp", models.DateTimeField()),
                ("ai_email_response", models.TextField()),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Resolved", "Resolved")],
                        default="Open",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelSpanishSpeakingCustomerQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("spreadsheet_row", models.IntegerField(null=True)),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=50, null=True)),
                ("customer_query_message_english", models.TextField(null=True)),
                ("customer_query_message_spanish", models.TextField(null=True)),
                ("customer_comments_english", models.TextField(null=True)),
                ("customer_comments_spanish", models.TextField(null=True)),
                ("ai_assistant_response_english", models.TextField(null=True)),
                ("ai_assistant_response_spanish", models.TextField(null=True)),
                ("laundry_event_details_english", models.TextField(null=True)),
                ("laundry_event_details_spanish", models.TextField(null=True)),
                ("location", models.CharField(max_length=150, null=True)),
                ("timestamp", models.DateTimeField()),
                ("ai_email_response_spanish", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Resolved", "Resolved")],
                        default="Open",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
