# Generated by Django 5.0 on 2025-08-05 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelInRoomRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=150, null=True)),
                ("phone_number", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("room_number", models.CharField(max_length=50, null=True)),
                ("request_type", models.CharField(max_length=50, null=True)),
                ("request_details", models.TextField()),
                (
                    "request_status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Resolved", "Resolved")],
                        default="Open",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
