# Generated by Django 5.0 on 2025-08-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0002_alter_customuser_email_alter_customuser_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotelinroomrequest",
            old_name="customer_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="hotelinroomrequest",
            name="last_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="hotelinroomrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Open",
                max_length=50,
                null=True,
            ),
        ),
    ]
