# Generated by Django 5.0 on 2025-09-21 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base_app",
            "0003_rename_customer_name_hotelinroomrequest_first_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, null=True)),
                ("work_email", models.CharField(max_length=150, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        default="profile_image/google-logo.png",
                        null=True,
                        upload_to="profile_image/",
                    ),
                ),
                ("department", models.CharField(max_length=150, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
