# Generated by Django 4.2.3 on 2025-09-22 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0004_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("Housekeeping", "Housekeeping"),
                    ("Front Desk", "Front Desk"),
                    ("Maintenance", "Maintenance"),
                    ("Management", "Management"),
                    ("Other", "Other"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
