# Generated by Django 4.2.3 on 2025-09-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0005_alter_employee_department_alter_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                choices=[
                    ("Housekeeping", "Housekeeping"),
                    ("Front Desk", "Front Desk"),
                    ("Food and Beverage", "Food and Beverage"),
                    ("Laundry", "Laundry"),
                    ("Maintenance", "Maintenance"),
                    ("Management", "Management"),
                    ("Other", "Other"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("Housekeeping", "Housekeeping"),
                    ("Front Desk", "Front Desk"),
                    ("Food and Beverage", "Food and Beverage"),
                    ("Laundry", "Laundry"),
                    ("Maintenance", "Maintenance"),
                    ("Management", "Management"),
                    ("Other", "Other"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
